version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-west-2"  # or your preferred region

cache:
  paths:
    # Cache pip dependencies
    - '/root/.cache/pip/**/*'  # Adjust if you have a custom location for pip cache
    # Cache node_modules
    - 'node_modules/**/*'  # Adjust if you have a custom location for npm cache

phases:
  install:
    commands:
      # Install Python and dependencies
      #- pip install --upgrade pip
      - cd cdk-dir

      - pip install -r requirements.txt

      # Install AWS CDK CLI
      - npm install -g aws-cdk

  pre_build:
    commands:
      # Set up your AWS credentials if needed (e.g., using environment variables)
      # export AWS_ACCESS_KEY_ID=<your-access-key>
      # export AWS_SECRET_ACCESS_KEY=<your-secret-key>

      # Optional: If this is the first time using the CDK, bootstrap the environment

      cdk bootstrap

  build:
    commands:
      # Synthesizing CloudFormation template
      - cdk synth

  post_build:
    commands:
      # Deploy the CDK stack
      - cdk deploy --require-approval never
